---
title: Tiny step for the human kind and a huge one for me entering the programming world.
date: 2018-06-21
---
author: n00man
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 30 years of jumping from thing to thing and now I have finally found my passion!

# social links
twitter_username: your-twitter-handle
github_username:  n00man

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
