title: WWAAD
date: 2018-06-21

author: Tsvetelin Todorov
email: tsvete.todorov@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Let me figure first why , then I will figure how.

# social links
twitter_username: your-twitter-handle
github_username:  n00man

show_excerpts: true # set to false to remove excerpts on the homepage

theme:
