title: Small step for the humanity and a huge step for me baby walking into GitHub.
author: n00man
email: tsvete.todorov@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  30 years jumping from thing to thing and now I really know what I wanna do with my life.
  Follow my journey through the wonderful world of programming.

# social links
twitter_username: your-twitter-handle
github_username: n00man

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
