title: to myself...
date: 2018-06-21

author: n00man
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 But how?

# social links
twitter_username: your-twitter-handle
github_username:  n00man

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
